### ISSUE TITLE
Users.js URL

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#1]
Mis aadressiga või ID'ga sai seda testi vaadata, mis me reedel lõime, kas see oli http://localhost:3000/users , http://localhost:3000/users8 , http://localhost:3000/users/8 või hoopis midagi muud?

**Comment by mitselek** [comment]
hetkel on http://localhost:3000/users8 tõesti :)

**Comment by r1987** [comment]
Mul annab millegipärast ikkagi errorit, kui users8 varianti brauseris taguda.

**Comment by mitselek** [comment]
Vaata, mis sul on app.js failis real 26

**Comment by r1987** [comment]
Ongi app.use('/users8', users); aga ikkagi http://localhost:3000/users8 annab 404.

**Comment by mitselek** [comment]
nu aga käsurealt ikka käivitasid nodemon'i?

**Comment by r1987** [comment]
jah:
Rannos-MacBook-Air:~ rannoait$ cd /Users/rannoait/saal-js
Rannos-MacBook-Air:saal-js rannoait$ nodemon ./bin/www
15 Apr 10:25:26 - [nodemon] v1.3.7
15 Apr 10:25:26 - [nodemon] to restart at any time, enter `rs`
15 Apr 10:25:26 - [nodemon] watching: *.*
15 Apr 10:25:26 - [nodemon] starting `node ./bin/www`
GET / 200 289.997 ms - 209
GET /stylesheets/style.css 304 2.739 ms - -
GET /users8 404 27.315 ms - 1086


- - -

Brauser:

Not Found

404

Error: Not Found
    at app.use.res.render.message (/Users/rannoait/saal-js/app.js:30:13)
    at Layer.handle [as handle_request] (/Users/rannoait/saal-js/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/Users/rannoait/saal-js/node_modules/express/lib/router/index.js:302:13)

jne.

**Comment by mitselek** [comment]
vaata, kas pele saal.entu.ee juures sisselogimist annab ika 404?

**Comment by mitselek** [comment]
oma gmaili kontoga saad sisse

**Comment by mitselek** [comment]
sa ikka kindlasti kasutad linki [http://localhost:3000/users8](http://localhost:3000/users8)?

**Comment by r1987** [comment]
Jaa, 100% http://localhost:3000/users8 . Ja ei aita ka see sisselogimine gmaili kontoga. Expressi esilehte kuvab, aga seda users8 asjaga ikkagi 404.

**Comment by r1987** [comment]
Nagu ma aru saan, siis sinul, Mihkel, asi kõik toimib?!

**Comment by mitselek** [comment]
toimib tõesti. Argo, oskad sina miskit arvata?

**Comment by argoroots** [comment]
Nu nõutakse ju ka user_id'd https://github.com/kgs-ee/saal-js/blob/master/routes/users.js#L9

**Comment by r1987** [comment]
OK, aga mis see siis tähendab, et nõutakse ka user_id? Pean ma midagi kuhugi kirjutama? Enda entu ID kuhugi panema? Brauseri url'is midagi lisama?

**Comment by mitselek** [comment]
igaks juhuks kontrolli, kas sinu masinas olev kood on syncis siin olevaga

**Comment by r1987** [comment]
Proovitud. 
Kustutatud korra git kaust arvutist ja uuesti kloonitud. Dependencied uuesti peale pandud, restarditud, uuesti käivitatud. Ei saa ette users8 lehte, 404 on.

**Comment by r1987** [comment]
Aga kuidas jääb siis?

Lehte https://saal.entu.ee/api2/entity-8 vaadates on samuti error. 

Mehed, ma ei saa aru, milles asi on. Ehk saate öelda lõppeks, mis valesti, või miks ei toimi. Minu aju rohkem ei võta seda probleemi lahendada, et üks lihtne asi ette saada.

**Comment by mitselek** [comment]
Kuule mulle näib, et me võiks korra koos kohvi juua, et kivi tagant lahti saada. Teisipäeval Kloostri Aidas (peale ärkamist)?

--

**Comment by r1987** [comment]
OK, aga mis kell siis? 10:00 sobib?

**Comment by mitselek** [comment]
sobib küll.

--

**Comment by r1987** [comment]
OK. Teeme siis nii.
