### ISSUE TITLE
Lisa : Residendid

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#10]
Väljadest tarvis:

* Video embbed väli (repeatable)
* Heli(soundcloud) embbed väli (repeatable)
* Residentuuri perioodi väli (kuupäev, näiteks Juuni—August 2015)
* Sisu väli

**Comment by mitselek** [comment]
Residendid võiks olla samuti _event_ tüüpi objektid ehk? nad lihtsalt asuksid "Residentuur" - nimelise _web-content_ 'i all.

**Comment by r1987** [comment]
Mhmh. täpselt. Need tunduvadki olevat täiesti eraldi asjad. Kohe teen projektide kohta selle sama issue.

**Comment by r1987** [comment]
Unus see osa mainida, et kas on võimalik residente ka nö. lahterdada mingi kategooria abil kanuti gildi saali ja pühavaimu saali residentideks?

(vaata: http://kgs-ee.github.io/saal-js/residencies.html)

**Comment by mitselek** [comment]
_web-content_ 'id selliselt hierarhiasse
- Koduleht
  - residentuur
    - KGS
    - Pühavaimu

**Comment by r1987** [comment]
Ok, tundub loogiline jah.
