### ISSUE TITLE
Lisa: Tuurid

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#11]
Võimalus/moodus tekitada SAAL'is olevast lavastusest ka Tuuri leheküljel kuvatav link. Seal peaks olema kirjas:

* Kuupäev
* Pealkiri
* Asukoht/teatri nimi
* Riik

(vaata; http://kgs-ee.github.io/saal-js/tours.html)

**Comment by mitselek** [comment]
Tuurid on samuti event tüüpi objektid, mis asuvad "Tuurid" - nimelise web-content 'i all.

**Comment by r1987** [comment]
Hmm… nii ja naa.

Mina olen asjast aru saanud niimoodi, et lavastus, või siis event võib minna ka tuurile. Seega on selliseid juhtumeid palju, et näiteks Henri Hüti ja Taavet janseni lavastus on Kanuti Gildi SAAL'is ära ja siis läheb näiteks tuurile Belgiasse, kus ta teeb 4 etendust ja siis Belgiast näiteks Saksamaale, kus teeb ühe. Kokkuvõtvalt tahan öelda seda, et sisu jääb lavastusel samaks, juurde tuleb Asukoht/teatri nimi ja Riik. Ära kaovad pileti müügi lahtrd.

Tuleb ikkagi eraldi objekt teha, või saab mingisuguse valikuga ka sama evendi juures mängida?

**Comment by mitselek** [comment]
nuneh, siis võib ju iga siukese tuuri kohta eraldi web-contenti jupi teha, kus tuuri-spetsiifiline lisainfo ja siis kõik tema all kõik vajalikud evendid. Igaks juhuks täpsustan, et Entus võib üks ja sama objekt asuda samaaegselt mitme _parent_ 'i all

**Comment by r1987** [comment]
Vist küll, kuigi tuurile minema evendi alla mingeid eraldi evente ei tule ja see tuuri-spetsiifiline lisainfo ongi ainult teater, riik ja toimumisajad/korrad.
