### ISSUE TITLE
Lisa: Projektid

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#12]
Väljadest tarvis:

* Projekti perioodi väli (kuupäev, näiteks Juuni—August 2015)
* Sisu väli
* Galerii

(vaata: http://www.saal.ee/event/551/ ja http://kgs-ee.github.io/saal-js/projects.html)

**Comment by mitselek** [comment]
Kas see projekt ei ole taas üks _event_ tüüpi asi?
- koduleht
  - projektid
    - _event_

Sõltub ka sellest, et kuidas me neid kalendrisse soovime kuvada.
Kuidas näeks välja üldkalender, kuhu me topime kokku kõik (_event_ * _parent_) kombinatsioonid?

**Comment by mitselek** [comment]
Me võime _web-content_ 'ile lisada välja nimega _color_ ja selle järgi saaksid vastavad sündmused kalendris endale värvi nt.

**Comment by r1987** [comment]
Küsin homme täpsemalt üle, kuidas need projekti asjad toimivad ikkagi. Aga kui minu mälu mind ei reeda, siis neid projekte on üldiselt harva ja need peavad kodukal olema kuvatud lihtsalt sellepärast, et peavad. Pigem on nende projektide juures tegu mingisuguste koostöövõrgustike ja koostöö projektidega, mille raames etenduvad mingisugused eraldiseisvad lavastused SAAL'is. Ma ise pigem näen seda eraldi objektina küll, kuid mitte väga sündmusena.

Kalender praegu toimib nii palju, et [copypasta](https://github.com/kgs-ee/saal-js/blob/master/src/javascripts/scripts.js#L125-L219) Norra etenduskunstide koduka veebist. Ma ise arvan, et võiks äkki color asemel lisada mingisuguse klassi, et see CSS'sis paika panna.

**Comment by mitselek** [comment]
CSS klass on hea lahendus. Ma ei teagi miks aga välja nimeks võib ikka 'color' panna :8ball:
