### ISSUE TITLE
Sündmused - tuurid - residendid

### ISSUE THREAD

**Issue by mitselek** [kgs-ee/saal-js#13]
Lapime kokku kõik väljad, mis sündmusel olema peavad:

#### _event_
- name - string
- description - text
- photo - file
- price - string  
  Arvatavasti tuleb hinnainfo PL'ist, kui sündmus on neile müüki antud
- time(*) - datetime
- duration - integer
- category - reference
- ticket-api - string  
  url PL API vastu. Näis kuidas me seda tegelikult lahendame
- location - string  
  Kuidagi peab saama kaetud ka stsenaarium, kus sama asja saab eri kohtades mängida
- video - text
- audio - text

**Comment by r1987** [comment]
Puudu on galerii ja tehniline info.

**Comment by mitselek** [comment]
audio, video ja teh.info välja tegin. galerii moodustugu ise, kui pilte on enam kui üks
