### ISSUE TITLE
nodemon app.js

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#16]
Hei,

Lehe saab lokaalvõrgus nüüd ikka samamoodi käima nagu ennegi, et terminalis käsklus nodemon app.js ?

Lisasin siin vahepeal mõned puudulikud dependencid package.jsoni, et funkama asi saada, kuid siiski saan errorit:

/Users/rannoait/GitHub/saal-js/app.js:28
if (!process.env.ENTU_URL) throw '"ENTU_URL" missing in environment'
                           ^
"ENTU_URL" missing in environment

**Comment by mitselek** [comment]
tõmba uus master ja käsurea saatsin sulle eraldi fleepi sõnumiga

-- 
Mihkel Putrinš
☎ +372 5656 0978
