### ISSUE TITLE
Festivalide leheküljed

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#19]
Millisel moel ja kuidas tuleks ära kujundada festivalide lehed?

**Comment by r1987** [comment]
Lisaks on veel see küsimus/probleem. Kõikidel festivalidel on üldiselt järgnevad lingid/väljad:
* Festivalist / About **(ca 300 sõna)**
  * Pressikajastus festivalist
* Piletid
* Toetajad (enamuses logod ja nimed)
* Kontakt
* Uudised (üsna mitmeid)
* Asukohad (google mapsi pinid kaardil)

Kuidas need väljad entus kajastuma hakkavad? On lihtsalt lisatud kuidagi kombinatsioonis festivali kirjelduse alla?

**Comment by mitselek** [comment]
Kui festivalipass on PL juures müügis, siis ta tekib meile kui "lavastus".
Lavastusel on PL juures kirjeldatud ka asukoht.
Töötame sellega?

**Comment by r1987** [comment]
Mis see siis tähendab. Festivalipass = sündmus nimega "Festivalipass" entus? : D

**Comment by mitselek** [comment]
eiei, sündmus nimega "festivali nimi", mille juures piletiinfo
