### ISSUE TITLE
kalendrikuupäeval klõpsates võiks minna kuupäevaotsingusse?

### ISSUE THREAD

**Issue by mitselek** [kgs-ee/saal-js#20]
http://localhost:3000/et/search?date=2015-09-05

**Comment by r1987** [comment]
Hmm… hea küss. Mõtlen et kas ei lähe äkki duubeldamiseks, kui sul juba on võimalik hiirega kalendrile liikudes näha, mis üritused toimuvad ja ka klikkida nende peal.

**Comment by mitselek** [comment]
lobiseme ikka fleepis
