### ISSUE TITLE
Programm: Uuemad ja vanemad lavastused ja filtreerimine

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#24]
Programmi lehel kuvataks siis hetkel oleva kuu etendusi. Nii ülesse kui alla olen ma pannud nupud, millega on võimalik navigeerida ajas edasi ja tagasi kuude kaupa. Vasakul on mul välja toodud nupud "Aasta" ja "Kategooria".

Valides Aasta nupust näiteks aasta 2013, hakkaks ta kuvama lavastusi aastast 2013 ja  jaanuari kuust (või siis hooaja algusest, mis on üldiselt septembri kuu). Teistes nuppudes muutuksid nupud näiteks August 2013 ja Oktoober 2013, et saaks navigeerida kuude kaupa.
**Kas see tundub loogiline sinu jaoks?**

Lisaks on nupp nimega "Kategooria", kust peaks olema võimalik linnukesi klõpsates filtreerida lavastusi vastavalt kuuluvusele. Viimane ei ole minu jaoks praegu väga loogiline, sest tegelikuses peaksid seal kõik linnukesed olema selekteeritud (probleem on minus, ei ole suutnud neid vaikimisi selekteerima panna ja ka kuvama dropdowni avatuna).

**Comment by mitselek** [comment]
et misjaoks üldse siukest aasta-kuu valimist tarvis on. või et kellele?

-- 
Mihkel Putrinš
☎ +372 5656 0978

**Comment by r1987** [comment]
Tegu oleks arhiiviga. Ma ei oska sellele küsimusele vastata täpselt, et kellele see väga vajalik on. Lõppeks on kõik arhiivid vajalikud tegelikuses eelkõige kunsti/teatri/tantsuteadlastele; google publicity kunstnikele/tantsijatele jms. Kas arvad, et on overkill säärane asi? Ma ise olen üsna avatud siin pakkumistele, kuidas seda lahendada. Minu jaoks võib see asi olla ka lihtsam. Hetkel olen mäletamistmööda lähtunud vistitsi SAAL'i inimeste soovidest, kuidas see asi ära lahendada.

**Comment by r1987** [comment]
Rääkisin siin just sel teemal ka Eveliniga. Teema on ikkagi see, et see oleks tegelikuses mõeldud kõigile ja põhimõtteliselt, kui see aasta filtreering liiga retsiks läheb, siis see ei ole nii oluline. Küll aga oleks hea, kui külastajal oleks võimalik filtreerida programmis olevaid sündmusi vastavalt nendele kategooriatele. Näiteks kui keegi tahab näha ainult tantsu etendusi või on viimane huvitatud ainult performanceitest.
