### ISSUE TITLE
Residentuur: SAAL + Pühavaimu residendid

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#25]
Residentide lehel peaksid residendid olema jaotatud kahte tulpa. Ühes on Kanuti Gildi SAALi residendid, teises Pühavaimu Saali residendid.

**Comment by mitselek** [comment]
https://saal.entu.ee/entity/folder/2109
asukoht võiks olla sündmuse küljes. sündmus on siis residendi viibimine asukohas. resident ise on lavastus.

Mis arvad, kas selline üldistus on liiast?
Kodulehel saab ju konteksti luua
