### ISSUE TITLE
Kontakt: Route, View

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#26]
Entusse oleks vaja välja, kuhu saaks sisestada SAALi töötajate kontaktandmed. Või kas äkki peaks kogu selle info tõmbama entu Persoonide kaustast? Sinna oleks siis muidugi vaja lisa välja **Telefoninumber**.

**Comment by mitselek** [comment]
Entu persoonid loomulikult

-- 
Mihkel Putrinš
☎ +372 5656 0978

**Comment by mitselek** [comment]
Person.phone väli tuleb kui veel ei ole

-- 
Mihkel Putrinš
☎ +372 5656 0978

**Comment by r1987** [comment]
Juurde oleks vaja ka ametinimetuse välja (eesti ja inglise keeles).

**Comment by mitselek** [comment]
Amet/Occupation
neid saab mitu tükki teha

**Comment by r1987** [comment]
Kas on võimalik ka mingeid persoone päringust mingil moel _excludeida_ ?

**Comment by r1987** [comment]
Ja mul on entus praegu see ametinimetuse väli hall ja ma ei saa seda aktiivseks hiirega klõpsides—peabki nii olema praegu?

**Comment by mitselek** [comment]
ametinimetus oli näpukas. korras see nüüd

**Comment by mitselek** [comment]
persoon kaob nimekirjast, kui ta Entus kaustast eemaldad (ülanoolenupp vastava persooni juures)

**Comment by r1987** [comment]
ok selge.

Aga arvan, et see ametinimetus vist peaks olema ka nii inglise keeles kui eesti keeles.

**Comment by mitselek** [comment]
ametinimetus nüüd kahes keeles

**Comment by r1987** [comment]
Kontakti all oleks vaja siis teha aktiivseks tesite töötajate informatsioon, mis puudu.

**Comment by mitselek** [comment]
Mine entusse ja anna kodulehele õigused

-- 
Mihkel Putrinš
☎ +372 5656 0978

**Comment by r1987** [comment]
Õigused on nagu kõigil seal "Public on the Web"

**Comment by mitselek** [comment]
"Public on the Web" tähendab, et kõik *avalikud* propertid on kõigile loetavad. *mitteavalikud* propertid on nähtavad ainult neile, kellele on eraldi ligipääsuõiguseid antud. Anni juures on ligipääsuõigus antud kasutajale "Koduleht" - teiste juures tal õiguseid pole.

**Comment by r1987** [comment]
Ok, sain isikud kätte, aga nende ametinimetusi ikka ei kuva.
