### ISSUE TITLE
Tõlked: Inglise keelsed väljad Entusse

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#27]
Puudu on veel tõlgete väljad Entus ja lahendus koduka poole peal.

**Comment by mitselek** [comment]
event
- description
- name
- technical-information
performance
- description
- name
- subtitle
- technical-information

**Comment by mitselek** [comment]
Sellised väljad said endale inglisekeelse paarilise

event
- description
- name
- technical-information

performance
- description
- name
- subtitle
- technical-information
