### ISSUE TITLE
Entu kuupäevade sisestamise probleem

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#28]
Toimumisaegade kuupäevi sisestades vahetab kuupäev ja kuu omavahel koha.

**Comment by mitselek** [comment]
See on Entu bugi - sokutan selle @argoroots kaela

**Comment by mitselek** [comment]
See bugi jääb määramata ajaks sisse. Sündmuse kuupäevi hakatakse sisestama PL kaudu.

**Comment by mitselek** [comment]
fixed in https://github.com/argoroots/Entu/commit/5d58c7d92a455ae57bf99d38a0db47fc814aabf1
