### ISSUE TITLE
Esietenduse väli või lahendus if/elsega?

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#29]
SAAL'i inimesed sooviksid lisada lisainformatsioonina etenduse juurde teinekord ka märke, et tegu on esietendusega.

Lisasin praegu [viimases commitis](https://github.com/kgs-ee/saal-js/commit/c67a058) koodi, mis võrdleb etenduse kuupäeva esimese start-time kuupäevaga:

```jade
if (moment(datestring).locale(lang).format('L')) === (moment(p["start-time"][0]).locale(lang).format('L'))
    p.today= t('button.premiere')
```

Probleem on sellega see, et ta lisab selle välja kõikidele sündmustele, mis ei ole vajalik, sest kohati nad sisestavad seda vanal kodukal ka muudele asjadele.

Kuidas asi lahendada?

**Comment by mitselek** [comment]
teeme esietenduse välja _performance.premiere_ ja see viitab siis _event_ 'ile

**Comment by mitselek** [comment]
et siis aja saab kätte nii nagu _event_ 'i käest ikka aint et esika event asub väheke sügavamal:
- `op.get(event, 'performance.premiere.start-time', [])` - kui esikat pole määratud, on tulemuseks tühi array
- `op.get(event, 'performance.premiere.start-time.0')` - kui esikat pole määratud, on tulemuseks _undefined_
