### ISSUE TITLE
Bännerite query + päringute järjestus

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#3]
https://saal.entu.ee/api2/entity?definition=banner näitab countina 0 ja ei kuva ka neid kolme bännerit, mis entus tegelikult olemas on. Mis parameetriga need bännerid ikkagi kätte saab?

Vaatasin entu wikist, et order_by parameeter on olemas, kuid mis väärtusega näiteks saab sündmusi järjestada nii, et hiljuti avaldatud postitusi kuvataks ees ja vanemaid taga pool?

https://saal.entu.ee/api2/entity?definition=event&limit=10&order_by= ???

**Comment by mitselek** [comment]
bännerite päring on õige.
tabaluku ikoonist sättisin bänneritele 'public' ligipääsu ja päring annab nüüd soovitud tulemuse.

**Comment by mitselek** [comment]
order_by toimib propertite pealt, nt. &order_by=name
kuupäevasordiks võid kasutada nt süsteemset propertit, mille järgi ise sorteerid:
``` javasctipt
"changed": {
  "dt": "2014-06-08 06:11:16",
  "ts": 1402207876
```

**Comment by mitselek** [comment]
Lahendatud: 767440af1e5f66887a8b860093beaf743d4f9e10.
