### ISSUE TITLE
Projektid

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#30]
Entuse oleks vaja tekitada ka veel üks kaust nimega projektid, kuhu ilmuksid sellised asjad nagu vanal lehel http://www.saal.ee/PROJEKTID/

Lisaks oleks siis neid vaja ka json kujul

**Comment by mitselek** [comment]
https://saal.entu.ee/entity/folder/2107
kas projekt on samade väljadega nagu lavastus?

-- 
Mihkel Putrinš
☎ +372 5656 0978

**Comment by r1987** [comment]
Peaaegu. 

Projektide juures ei ole vaja selliseid välju nagu:
*  Tehniline info(est) + Tehniline info(eng)
* Raiderid
* Hind
* Müügil alates
* Hind alates
* Müügi staatus
* Hind kuni
* Piletid

Tegu on lihtsalt kirjeldavate lehtedega ja sarnane rohkem residentuuri layoutile.

**Comment by mitselek** [comment]
nu ärgem siis täitkem mittevajalikke välju ja vaatame, kas sobib.
kui selgub, et ei sobi, siis uut objektityypi saab suht on-the-fly teha ilma kadudeta

**Comment by r1987** [comment]
OK, selge pilt!
