### ISSUE TITLE
Üksiku sündmuse piletimüügi lingid puudu

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#31]
Kui klikkida mõnel sündmusel, kuvab ta selle üksikul vaatel paremal selle sama ürituse piletilinki, kuigi peaks kuvama kõiki tulevasi lavastusega seotud sündmusi nagu ennist.

```jade
aside.col-md-4.col-lg-3
                .row
                    each datestring in op.get(event, 'start-time', [])
                        if datestring >= ((moment(Date.now()).format('YYYY-MM-DD HH:mm')))
                            .col-xs-6.col-md-6
                                p= (moment(datestring).locale(lang).format('dddd'))
                                p= (moment(datestring).locale(lang).format('L'))
                                p= (moment(datestring).locale(lang).format('HH:mm'))
                            .col-xs-6.col-md-6.text-right
                                a.btn.btn-primary(href='#') Osta pilet

                            .col-xs-12.col-md-12.col-lg-12
                                hr
```

**Comment by mitselek** [comment]
see on ju konkreetse sündmuse vaade. kõigi sündmuste inff oleks loogiline lavastuse lehel näidata? Või olgu see sündmuse vaade siuke combo-vaade, kuhu lisaks konkreetsele sündmusele kuvatakse piletiostulinke ka sama lavastuse tulevastele sündmustele?

**Comment by r1987** [comment]
Tõsi. Ongi konkreetse sündmuse vaade. Mulle endale tundub loogiline, et isegi kui klikid täitsa eraldi sündmusel, siis ta kuvab ka kõiki tulevasi asju. Lähed siiski ju ka infot selle lavastuse kohta lugema, siis on jälle võimalik paremal ka kõigi kuupäevadega tutvuda ja pilet ära osta.

**Comment by r1987** [comment]
Mingis mõttes oleks see loogika selline, et esilehel ja programmi lehel küll kuvatakse listina kõiki sündmusi, aga nad lingivad alati lavastuse lehele.
