### ISSUE TITLE
Kui mõni sündmus/etendus/etteaste on tasuta?

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#32]
Kas selle jaoks peaks olema kuskil Entus võimalik teha linnuke ja seejärel tegema if küsimuse koodis enne pileti nupukest ja hinda?

**Comment by mitselek** [comment]
no kui hind on null, siis ongi tasuta?

**Comment by r1987** [comment]
Praegu on ka selline juhus, et kus EKKE MOOR on välja müüdud ja piletilevi on seega pannud hinnaks 0€
