### ISSUE TITLE
Kalender: json genereerib valesi linke

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#33]
Tundub, et kalendri router ei genereeri linke otse lavastusele, vaid üksikutele sündmustele. Samuti on minu meelest listist puudu ka tuuril olevad lavastused.

**Comment by mitselek** [comment]
seal, kus linki genereeritakse, kasuta event.id asemel midagi sellist:
```
if op.get(event, 'performance.id', false)
   a(href='http:saal.ee/performance/' + op.get(event, 'performance.id'))
```

**Comment by r1987** [comment]
?

Mulle endale tundub, et äkki on asi kalendri controlleris, mis ei tee äkki sama asja, mis esilehel olevate sündmustega?

**Comment by r1987** [comment]
Mul peaks kuskil pagecache kaustas olema ka calendar.json fail eksole.

**Comment by r1987** [comment]
Tekivad mingid muud imelikud errorid. Kui lisada [scripts.js](https://github.com/kgs-ee/saal-js/blob/master/public/javascripts/scripts.js#L50-L54) failis kõigile ka performance vahele, tekib kuupäevaga tagasi liikudes uus error:

'''
[Error] TypeError: undefined is not an object (evaluating 'event.performance.id')
'''

**Comment by mitselek** [comment]
osadel eventidel pole performancet. neil siis ära linki tee
