### ISSUE TITLE
Lisa väli: Kunstnik/Produtsent/Linn

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#35]
Vaja oleks lisavälja nimega Kunstnik/Produtsent/Linn.

Peaks olema nähtav nendest kaustades:
* Lavastused
* Sündmused
* Tuurid
* Residentuurid

**Comment by mitselek** [comment]
- Kunstnik on lavastuse info;
- Produtsent on lavastuse või sündmuse info?
- Linn on sündmuse info?

**Comment by r1987** [comment]
See kontekst on vist tegelikult rohkem selline pealkirja tarbeks ja toimib nagu too alapealkiri

Näiteks: *Alissa Šneider / Priit Raud / Tallinn, EE*
