### ISSUE TITLE
Featured indenti probleem?

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#36]
Esilehel olev slider ning selle sees olevad kategooriad, mis käivad iga sündmuse kohta, kompileerib jade millegipärast täiesti valesti. Kehtib see just esilehe kohta, sest mujal on kasutatud sama koodi ning toda probleemi ei esine.

**Comment by mitselek** [comment]
et sel puhul me tahame näidata event’i lehte (mida meil hetkel enam pole)?

nu siis tee sinna 
:::
IF event.performance
    link to performance/event.performance.id
else
    link to event/event.id

ja teeme sellel eventi lehe uuesti

-- 
Mihkel Putrinš
☎ +372 5656 0978
