### ISSUE TITLE
Tuuride arhiiv

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#40]
Ma arvan, et seal võiks informatsioon olla sarnaselt jaotatud nagu Kava all, aga ilma tolle kategooria filtreeringuta. Seega võiks seal olla:

- [] Aasta filtreering
- [] Kuu filtreering navigatsioonina

**Comment by mitselek** [comment]
kle tuleta mulle meelde, milleks seda aasta filtreeringut ikka tarvis oligi

-- 
Mihkel Putrinš
☎ +372 5656 0978
