### ISSUE TITLE
SAAL kategooriad etenduste fotodel

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#43]
Hetkel kuvab ta seal ainult neid kategooriad, mis on määratud entus, kuid toimima peaks ta ikkagi nii, et kuvatataks kõiki määratuid kategooriaid ning kriipsutaks läbi need, mis antud lavastuse kohta ei käi.

Varasem näide, kuidas asi funktsioneeris ja kuidas ta peaks funktsioneerima ka nüüd:
https://github.com/kgs-ee/saal-js/blob/3d9413ce742e7faf510b63564d8f39fd93c42504/views/performance.jade#L18-L40

**Comment by mitselek** [comment]
minuarust just nii toimibki hetkel?

**Comment by mitselek** [comment]
või pead sa silmas seda, et siin http://localhost:3000/et/performance/2103 peaks olema samamoodi nigu pealehel?

**Comment by r1987** [comment]
Ma mõtlen, et sellel näitel, mis sa näitad, peaks olema ka esilehel ja igal pool mujal. See tähendab, et korraga võiks olla näha kõik 6 kategooriat ja siis on läbikriipsutatud need, mis ei ole lavastuses kategooriateks määratud.
