### ISSUE TITLE
Lavastustele lisaväli "Asukoht"

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#45]
Lisaväli nimega *Asukoht* tuleks lisada ka lavastustele. Seal on vaja teha vahet, kas lavastus toimub Kanuti Gildi SAAL'is või Pühavaimu SAALis. Toimiks teine sarnaselt siis tuuridegagi, et toda asukohta kuvataks piletihinna peal.

**Comment by mitselek** [comment]
Sellest ma ei saa aru. Lavastus ei ole ju asukohas - selleks on sündmus ometi

**Comment by r1987** [comment]
Hmm… tead, see võib mu error täiesti olla küll. Äkki on kõik ok selle asjaga.
