### ISSUE TITLE
Bänneriväli esilehele

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#46]
Esilehe tarbeks oleks vaja üht bännerivälja, kuhu saaks lisada Kino Sõpruse bännerit. Praeguse seisuga oleks see vaja ilmutada "tule vabatahtlikuks" nupu alla. SAAL'i inimesed hakkaksid seda ise igakord vahetama, kui vajadus tekib. 

Lisada on see väli vaja sellepärast, et Kino Sõprus reklaamib SAAL'i sündmusi samamoodi oma lehel.

**Comment by mitselek** [comment]
lisa siia uus banneri tüüp kõigepealt:
https://saal.entu.ee/entity/banner/2786

**Comment by mitselek** [comment]
asusin ise tegema

**Comment by mitselek** [comment]
resolved in 1aaec79a1d198d92b3944d529766da1bb40a3500
