### ISSUE TITLE
Residentuurid eemaldada calendar_jsonist

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#47]

**Comment by mitselek** [comment]
palun kontrolli, kas sai korda

**Comment by r1987** [comment]
Tundub, et nagu oleks ikka veel alles. Vähemalt web inspectoris ta näitab, et tekitab veel touri classi.

**Comment by mitselek** [comment]
kusse tekib - kuidas ma seda näen?

**Comment by r1987** [comment]
Võta paremalt kalendrist Oktoober ja siis 12 kuupäev on punast värvi ja kui web inspectoriga vaadata, siis on seal näha, et üks ekstra class on lisatud.

![screen shot 2015-11-30 at 11 14 48](https://cloud.githubusercontent.com/assets/8476564/11467869/c9d2a8a2-9753-11e5-8fcd-eb992512f2ca.png)
