### ISSUE TITLE
Otsingu probleem. Otsides kuvab leitud arvu, kuid mitte linke

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#49]
Esilehel otsingusse näiteks Alissa kirjutades, kuvab ta otsingu lehel mul OTSISID: ALISSA • LEIDSIN 17, kuid linke seal all ei kuvata.

**Comment by mitselek** [comment]
mis siis nüüd

**Comment by r1987** [comment]
Ikkagi on mingi jama. Otsides ei kuva pealkirju täpselt ja kui ma vajutan piltid epeal olevatele katgooriatele, siis kuvab ta otsingu tulemust, aga linke nende asjadeni ei kuva.

**Comment by mitselek** [comment]
aha!
sama häda mis tavaotsingul arvatavasti

**Comment by r1987** [comment]
ok!

**Comment by mitselek** [comment]
http://saal.entu.eu/et/search?q=category:Tants
