### ISSUE TITLE
Lisa väli: Soundcloud/heli embbed

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#6]
Tarvis oleks samasugust embed välja nagu hetkel videodel.

**Comment by mitselek** [comment]
ot kusse embed väli meil olemas on?

**Comment by r1987** [comment]
![screen shot 2015-07-15 at 22 57 28](https://cloud.githubusercontent.com/assets/8476564/8708490/f77fa28a-2b44-11e5-9721-05a6ac8873ef.png)

**Comment by mitselek** [comment]
o, sa oled web-content objekti avastanud? vau

**Comment by r1987** [comment]
?

**Comment by mitselek** [comment]
eino ma rõõmustan, et sa asjal silma peal hoiad.
heliväli olemas.

**Comment by r1987** [comment]
Justjust. Tglt ma sinna fleepi kirjutasin ka, et kas see on õige koht nüüd, kuhu infot sisestada?

**Comment by r1987** [comment]
Kas peale soundcloudi linkide on ka võimalik kuidagi heli embeddida?

Toome näite, et kui tuleb mõni kunstnik, kellel ei ole helilahendust soundcloudis, vaid tal on edastada ainult mp3 fail. Kuidas siis tuleks käituda?
