### ISSUE TITLE
Firefoxiga ei tööta gradientmaps üksikutel lehtedel

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#66]
Välja peilitud probleem tundub olevat veider. <base href=…> tagi eemaldamisel hakkab mozillas asi tööle.

**Comment by mitselek** [comment]
Ranno Ait / 9:18
---
hmm hmm hmmm: http://stackoverflow.com/a/7762874
ja see vastus: http://stackoverflow.com/a/19753427

**Comment by mitselek** [comment]
@r1987 reprted this on gradientmaps repository https://github.com/awgreenblatt/gradientmaps/issues/4

**Comment by mitselek** [comment]
Kas ikka ei tööta?

**Comment by r1987** [comment]
Autor ei ole vastanud, ma tegin ise hacki sellele pluginale ja peaks toimima

**Comment by r1987** [comment]
Insufficient dialog with plug-in author.
