### ISSUE TITLE
Automaatne galerii fotode genereerimine

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#67]
Seda oleks ikka tulevikus vaja. Praegu galeriides originaalpildid väga suured ja laadimine võtab kaua aega.

**Comment by mitselek** [comment]
Sellega tegeleme Entu poole pealt. 
Teema on natuke suurem ja võtab veidi aega.

**Comment by r1987** [comment]
OK

**Comment by mitselek** [comment]
https://github.com/mitselek/pildimaag/releases/tag/1.0.0-beta1
pildimaag on laivis
