### ISSUE TITLE
Lisa väli: Pressikajastus

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#7]
Tarvis oleks Lingi nime ja lingi välja.

(vaata: http://kgs-ee.github.io/saal-js/single-event.html)

**Comment by mitselek** [comment]
event’i külge?

-- 
Mihkel Putrinš
☎ +372 5656 0978

**Comment by r1987** [comment]
Jah.

**Comment by mitselek** [comment]
pressikajastust võib tulla sündmuse kohta enam kui üks. ning pressikajastus võib käsitleda mitut sündmust.
tuleb teha eraldi objekt, mis saab viidata seotud sündmustele
