### ISSUE TITLE
Lisa väli: Galerii

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#8]
Tarvis oleks lavastuse galerii lahendust/väljasi.

(vaata: http://kgs-ee.github.io/saal-js/single-event.html)

**Comment by mitselek** [comment]
Kui galerii all pead silmas fotosid, siis _photo_ välja sisse võib mitu faili panna ja layout siis mitme puhul kuvab galeriina?

**Comment by r1987** [comment]
Jah. Kui nii saab, siis väga hästi.

**Comment by r1987** [comment]
Kuid kuidas genereeruvad galerii thumbnailid? Kuskilt ajusopist mäletan, et entus vist ei olnud seda varianti, et lisad pildi ja siis ta teeb ühest pildist a la 5 erineva suurusega asja?!

**Comment by mitselek** [comment]
saab olema selline asi

-- 
Mihkel Putrinš
☎ +372 5656 0978

**Comment by mitselek** [comment]
okumuuseumis olen kasutanud mitme pildi olemasolul siukest karusselli:
https://okupatsioon.entu.ee/public-fond/entity-92378/f000064-002-meene-onnitluskaart
