### ISSUE TITLE
Lisa väli: Tehniline info

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#9]
Tarvis oleks lisa sisu välja Entusse, kuhu saab kirjutada lisainfo lavastuse kohta (näitlejad, tantsijad, valgus, video, keel jne.)

(vaata: http://kgs-ee.github.io/saal-js/single-event.html)

**Comment by mitselek** [comment]
Need peaks kõik olema mingite inimestega seotud väljad?

**Comment by mitselek** [comment]
Laval püsti: Charlekas, Meelis Kubo, Harri, tuvigäng
    Lava taga pikali: Henrik Kalmet, Paavo Piik, Paul Piik
    Valgus/tehniline abi: Revo Koplus
    Video: Rainar Aasrand
    Kujundus: Brit Pavelson
    Produtsent: Kinoteater
    Eesti keeles

Kas see inff peab detailselt struktureeritud olema või piisab ka _technical-information_ tekstiväljast?

**Comment by r1987** [comment]
Lihtsalt technical-information tekstiväli on küll. See on eraldi väljana mul sellepärast, et kujunduslikult on ta piletiinfo all. Nimesid ja asju pole vaja siduda kuidagi.
