### ISSUE TITLE
"Teised tööd" pealkiri kuvatakse lehel, kuigi koodi järgi seda ei tohiks kuvada

### ISSUE THREAD

**Issue by r1987** [kgs-ee/saal-js#96]
Siin justkui ju kood eeldab _performance.jade_ faili juures, et seda TEISED TÖÖD pealkirja kuvatakse, *kui on* midagi kuvada:
```jade
if op.get(performance, ['otherWorks'], false)
                    .related-perfomance
                        h2= t('title.related')
```
Aga pealkirja ikkagi kuvatakse näiteks siin https://saal.ee/et/performance/4118 .

**Comment by mitselek** [comment]
https://github.com/kgs-ee/saal-js/blob/master/views/performance.jade#L51
